name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: build libs
      run: libs/build.sh
    - name: make
      run: make -B -C src dirs solver test
    - name: test
      run: src/test
